### ISSUE TITLE
Hover area to trigger composing is obstructive

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#12]
If window width is below 860 / 850 px the quick compose controls get int the way of my life.

In the screenshot attached, hovering on the 'bin' icon is causing the menu to expand and blocks access to the message controls.

<img width="840" alt="screen shot 2017-01-15 at 09 46 40" src="https://cloud.githubusercontent.com/assets/10211530/21961662/99b34b2e-db07-11e6-8dc2-c2a927767862.png">

**Comment by mattpilott** [comment]
This is fixed in [6de0ed2](https://github.com/matt3224/inbox/commit/6de0ed2d46da4dfcad41722db4102ad08bd18dcc)
