### ISSUE TITLE
Sidebar width is 250px

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#13]
Feels unnecessarily wide compared with Boxy's 190px width. Perhaps shrink? 
<img width="427" alt="screen shot 2017-01-15 at 09 58 48" src="https://cloud.githubusercontent.com/assets/10211530/21961716/679472ba-db09-11e6-93f5-a5cc1e5dcf69.png">

**Comment by mattpilott** [comment]
I actually decided to make it wider as i think that inbox has it too slim
