### ISSUE TITLE
Icon positioning issue

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#14]
<img width="316" alt="screen shot 2017-01-17 at 09 58 12" src="https://cloud.githubusercontent.com/assets/10211530/22015839/98babe92-dc9b-11e6-843e-c9f0926e271c.png">

**Comment by mattpilott** [comment]
Fixed in: [253f9e4](https://github.com/matt3224/inbox/commit/253f9e4916ea6823a3a183e5135e0838f1544387)
