### ISSUE TITLE
Weird grey bar if resizing the window

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#5]
![screen_shot_2017-01-15_at_09_11_51](https://cloud.githubusercontent.com/assets/10211530/21961505/1803277e-db03-11e6-85ed-6be3eac6805c.png)

**Comment by ChippyWhips** [comment]
Only if sidebar is collapsed and window is being dragged from the left hand side. 

Grey bar is visible on drag cursor, so hover as well as during the actual resizing.

**Comment by mattpilott** [comment]
Fixed in [68a4f4e](https://github.com/matt3224/inbox/commit/68a4f4ede3fa6788fea17d3b2d22f27eb8ff7210)
