### ISSUE TITLE
Header of app has different shades of blue.

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#6]
Mainly visible on the right of the search bar around the pin toggle.

**Comment by ChippyWhips** [comment]
<img width="455" alt="screen shot 2017-01-15 at 09 16 28" src="https://cloud.githubusercontent.com/assets/10211530/21961513/54a681d0-db03-11e6-9768-0040d16782c1.png">

**Comment by mattpilott** [comment]
Maybe fixed in [68a4f4e](https://github.com/matt3224/inbox/commit/68a4f4ede3fa6788fea17d3b2d22f27eb8ff7210)
