### ISSUE TITLE
Weird menu toggle 'active state' positioning

### ISSUE THREAD

**Issue by ChippyWhips** [matt3224/inbox#7]
<img width="1229" alt="screen shot 2017-01-15 at 09 17 21" src="https://cloud.githubusercontent.com/assets/10211530/21961525/a6f73182-db03-11e6-9b69-32906626c466.png">

**Comment by ChippyWhips** [comment]
Top right, dark circle. wtf.

**Comment by mattpilott** [comment]
Fixed in [68a4f4e](https://github.com/matt3224/inbox/commit/68a4f4ede3fa6788fea17d3b2d22f27eb8ff7210)
